config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :tasks do
      member do
        patch :complete
      end
    end
  end
  root 'projects#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :tasks
    validates :title, presence: true
    validates :desc, presence: true, length: { minimum: 10 }
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  def completed?
    !completed_at.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy!

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :desc)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :set_project
    before_action :set_task, except: [:create]
    def create
        @task=@project.tasks.create(task_params)
        redirect_to @project
    end
    def destroy
        if @task.destroy
            flash[:success]="Task Deleted Succesfully!"
        else
            flash[:error]="Task was not deleted!"
        end
        redirect_to @project
    end
    def complete
        @task.update_attribute(:completed_at, Time.now)
        redirect_to @project,notice: "Task Completed."
    end
    private
    def set_project
        @project= Project.find(params[:project_id])
    end
    def set_task
        @task=@project.tasks.find(params[:id])
    end
    def task_params
        params[:task].permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>

<body>
  <header>
      <nav class="navbar navbar-expand-lg " ;">
      <div class="container-fluid">
        <%= link_to 'Project Management ',root_path,class:"navbar-brand fs-2 mx-5"%>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      </div>
    </nav>
  </header>
  <div class="container">
    <%= yield %>
  </div>
  <footer class="mt-4">
    <span>
    <a href="#">Project Management </a> |2024 All Rights Reserved.</span>
  </footer>

  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script>
    $('document').ready(function(){ 
      $('.alert').fadeOut(5000);
      $('.btn-close').click(function(){
        $('.alert').slideUp();
      })
     })
  </script>

app/views/projects/_form.html.erb
<%= form_for(@project) do |form| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
        <% @project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title%> <br>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :desc, style: "display: block" %>
    <%= form.text_area :desc %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Title:</strong>
    <%= project.title %>
  </p>

  <p>
    <strong>Desc:</strong>
    <%= project.desc %>
  </p>

</div>

app/views/projects/edit.html.erb
<h1 class="todo_list_title">Editing project</h1>

<div class="forms">
	<%= render 'form' %>
</div>
<div class="links">
  <%= link_to "Back to projects", root_path %>
</div>

app/views/projects/index.html.erb
<% @projects.each do |project| %>
  <div class="index_row clearfix">
    <h2 class="todo_list_title"><%= link_to project.title, project %></h2>
    <p class="todo_list_sub_title"><%= truncate(project.desc, length: 200) %></p>
  </div>
  <% end %>
  <div class="links">
    <%= link_to "New Project",new_project_path %>
  </div>

app/views/projects/new.html.erb
<h1 class="todo_list_title">New project</h1>
<div class="forms">
<%= render "form", project: @project %>
</div>
<div class="links">
  <%= link_to "Back to projects", root_path %>
</div>

app/views/projects/show.html.erb
<h2 class="todo_list_title"><%= @project.title %></h2>
<p class="todo_list_sub_title"><%= @project.desc %></p>
<div id="todo_items_wrapper">
  <%= render @project.tasks %>
  <div id="form">
  <%= render 'tasks/form' %>
  </div></div>
<div class="links">
  <%= link_to "Edit this project", edit_project_path(@project) %> |
  <%= link_to "Back to projects", projects_path %>
  <%= button_to "Destroy this project", @project, method: :delete %>
</div>

app/views/tasks/_form.html.erb
<%= form_for([@project, @project.tasks.build]) do |f| %>
<div class="mb-3">
    <%= f.label :"Task :",class:"form-label"%>
    <%= f.text_area :content,placeholder:"New Task",required:true,class:"form-control"%>
</div>
<%= f.submit "Add Task"%>
<% end %>

app/views/tasks/_task.html.erb
<div class="row clearfix">
    <%if task.completed? %>
        <div class="complete">
            <%= link_to complete_project_task_path(@project, task.id),data: {turbo_method: 'patch', turbo_confirm: "Are you sure"} do%>
            <i style="opacity:0.4;" class="fa-solid fa-check"></i>
            <% end %>
        </div>
        <div class="todo_item">
            <p style="opacity:0.4"><strike><%= task.content %></strike></p>
        </div>
        <div class="trash">
            <%= link_to project_task_path(@project, task.id),data: {turbo_method: 'delete', turbo_confirm: "Are you sure"} do%>
            <i class="fa-solid fa-trash"></i>
            <% end %>
        </div>
    <% else %>
        <div class="complete">
            <%= link_to complete_project_task_path(@project, task.id),data: {turbo_method: 'patch', turbo_confirm: "Are you sure"} do %>
            <i class="fa-solid fa-check"></i>
            <% end %>
        </div>
        <div class="todo_item">
            <p><%= task.content %></p>
        </div>
        <div class="trash">
            <%= link_to project_task_path(@project, task.id),data: {turbo_method: 'delete', turbo_confirm: "Are you sure"} do %>
            <i class="fa-solid fa-trash"></i>
            <% end %>
        </div>
    <% end %>
  </div>